CREATE TABLE "TBL_RETAILER" (
	"RETAILER_ID" INT NOT NULL,
	"BUSINESS_NAME" VARCHAR2(255) NOT NULL,
	"RETAILER_EMAIL" VARCHAR2(255) NOT NULL,
	"RETAILER_MOBILE_NO" VARCHAR2(10) NOT NULL,
	constraint TBL_RETAILER_PK PRIMARY KEY ("RETAILER_ID"));

CREATE sequence "TBL_RETAILER_RETAILER_ID_SEQ";

CREATE trigger "BI_TBL_RETAILER_RETAILER_ID"
  before insert on "TBL_RETAILER"
  for each row
begin
  select "TBL_RETAILER_RETAILER_ID_SEQ".nextval into :NEW."RETAILER_ID" from dual;
end;

/
CREATE TABLE "TBL_USER" (
	"USER_ID" INT NOT NULL,
	"NAME" VARCHAR2(20) NOT NULL,
	"EMAIL" VARCHAR2(255) NOT NULL,
	"ADDRESS" VARCHAR2(255) NOT NULL,
	"CITY" VARCHAR2(20) NOT NULL,
	"PINCODE" VARCHAR2(20) NOT NULL,
	"PASSWORD" VARCHAR2(255) NOT NULL,
	"MOBILE_NO" VARCHAR2(10) NOT NULL,
	constraint TBL_USER_PK PRIMARY KEY ("USER_ID"));

CREATE sequence "TBL_USER_USER_ID_SEQ";

CREATE trigger "BI_TBL_USER_USER_ID"
  before insert on "TBL_USER"
  for each row
begin
  select "TBL_USER_USER_ID_SEQ".nextval into :NEW."USER_ID" from dual;
end;

/
CREATE TABLE "TBL_PRODUCT" (
	"PRODUCT_ID" INT NOT NULL,
	"PRODUCT_NAME" VARCHAR2(255) NOT NULL,
	"PRODUCT_QUANTITY" INT NOT NULL,
	"PRICE" BINARY_DOUBLE NOT NULL,
	"PRODUCT_DESCP" VARCHAR2(255) NOT NULL,
	"CATEGORY_ID" INT NOT NULL,
	"PRODUCT_STATUS" VARCHAR2(255) NOT NULL,
	"PRODUCT_IMG" VARCHAR2(255) NOT NULL,
	"RETAILER_ID" INT NOT NULL,
	constraint TBL_PRODUCT_PK PRIMARY KEY ("PRODUCT_ID"));

CREATE sequence "TBL_PRODUCT_PRODUCT_ID_SEQ";

CREATE trigger "BI_TBL_PRODUCT_PRODUCT_ID"
  before insert on "TBL_PRODUCT"
  for each row
begin
  select "TBL_PRODUCT_PRODUCT_ID_SEQ".nextval into :NEW."PRODUCT_ID" from dual;
end;

/
CREATE TABLE "TBL_ORDER" (
	"ORDER_ID" NUMBER(12, 0) NOT NULL,
	"USER_ID" INT NOT NULL,
	"DATE" DATE NOT NULL,
	"ORDER_TOTAL_PRICE" BINARY_DOUBLE NOT NULL,
	constraint TBL_ORDER_PK PRIMARY KEY ("ORDER_ID"));

CREATE sequence "TBL_ORDER_ORDER_ID_SEQ";

CREATE trigger "BI_TBL_ORDER_ORDER_ID"
  before insert on "TBL_ORDER"
  for each row
begin
  select "TBL_ORDER_ORDER_ID_SEQ".nextval into :NEW."ORDER_ID" from dual;
end;

/
CREATE TABLE "TBL_CATEGORY" (
	"CATEGORY_ID" INT NOT NULL,
	"CATEGORY_NAME" VARCHAR2(255) NOT NULL,
	constraint TBL_CATEGORY_PK PRIMARY KEY ("CATEGORY_ID"));

CREATE sequence "TBL_CATEGORY_CATEGORY_ID_SEQ";

CREATE trigger "BI_TBL_CATEGORY_CATEGORY_ID"
  before insert on "TBL_CATEGORY"
  for each row
begin
  select "TBL_CATEGORY_CATEGORY_ID_SEQ".nextval into :NEW."CATEGORY_ID" from dual;
end;

/
CREATE TABLE "TBL_USERCART" (
	"CART_ID" INT NOT NULL,
	"TOTAL_ITEM" INT NOT NULL,
	"TOTAL_PRICE" BINARY_DOUBLE NOT NULL,
	"USER_ID" INT NOT NULL,
	constraint TBL_USERCART_PK PRIMARY KEY ("CART_ID"));

CREATE sequence "TBL_USERCART_CART_ID_SEQ";

CREATE trigger "BI_TBL_USERCART_CART_ID"
  before insert on "TBL_USERCART"
  for each row
begin
  select "TBL_USERCART_CART_ID_SEQ".nextval into :NEW."CART_ID" from dual;
end;

/
CREATE TABLE "TBL_CART_ITEM" (
	"PRODUCT_ID" INT NOT NULL,
	"QUANTITY" INT NOT NULL,
	"UNIT_PRICE" BINARY_DOUBLE NOT NULL,
	"CART_ITEM_ID" INT NOT NULL,
	"CART_ID" INT NOT NULL,
	constraint TBL_CART_ITEM_PK PRIMARY KEY ("CART_ITEM_ID"));

CREATE sequence "TBL_CART_ITEM_ID_SEQ";

CREATE trigger "BI_TBL_CART_ITEM_ID"
  before insert on "TBL_CART_ITEM"
  for each row
begin
  select "TBL_CART_ITEM_ID_SEQ".nextval into :NEW."CART_ITEM_ID" from dual;
end;

/
CREATE TABLE "TBL_ORDER_ITEM" (
	"ORDER_ITEM_ID" INT NOT NULL,
	"ORDER_QUANTITY" INT NOT NULL,
	"ORDER_UNIT_PRICE" BINARY_DOUBLE NOT NULL,
	"ORDER_STATUS" VARCHAR2(255) NOT NULL,
	"ORDER_ID" INT NOT NULL,
	"PRODUCT_ID" INT NOT NULL,
	constraint TBL_ORDER_ITEM_PK PRIMARY KEY ("ORDER_ITEM_ID"));

CREATE sequence "TBL_ORDER_ITEM_ID_SEQ";

CREATE trigger "BI_TBL_ORDER_ITEM_ID"
  before insert on "TBL_ORDER_ITEM"
  for each row
begin
  select "TBL_ORDER_ITEM_ID_SEQ".nextval into :NEW."ORDER_ITEM_ID" from dual;
end;

/


ALTER TABLE "TBL_PRODUCT" ADD CONSTRAINT "TBL_PRODUCT_fk0" FOREIGN KEY ("CATEGORY_ID") REFERENCES "TBL_CATEGORY"("CATEGORY_ID");
ALTER TABLE "TBL_PRODUCT" ADD CONSTRAINT "TBL_PRODUCT_fk1" FOREIGN KEY ("RETAILER_ID") REFERENCES "TBL_RETAILER"("RETAILER_ID");

ALTER TABLE "TBL_ORDER" ADD CONSTRAINT "TBL_ORDER_fk0" FOREIGN KEY ("USER_ID") REFERENCES "TBL_USER"("USER_ID");


ALTER TABLE "TBL_USERCART" ADD CONSTRAINT "TBL_USERCART_fk0" FOREIGN KEY ("USER_ID") REFERENCES "TBL_USER"("USER_ID");

ALTER TABLE "TBL_CART_ITEM" ADD CONSTRAINT "TBL_CART_ITEM_fk0" FOREIGN KEY ("PRODUCT_ID") REFERENCES "TBL_PRODUCT"("PRODUCT_ID");
ALTER TABLE "TBL_CART_ITEM" ADD CONSTRAINT "TBL_CART_ITEM_fk1" FOREIGN KEY ("CART_ID") REFERENCES "TBL_USERCART"("CART_ID");

ALTER TABLE "TBL_ORDER_ITEM" ADD CONSTRAINT "TBL_ORDER_ITEM_fk0" FOREIGN KEY ("ORDER_ID") REFERENCES "TBL_ORDER"("ORDER_ID");
ALTER TABLE "TBL_ORDER_ITEM" ADD CONSTRAINT "TBL_ORDER_ITEM_fk1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "TBL_PRODUCT"("PRODUCT_ID");

